import "dotenv/config";
import { toJSONAsync } from "seroval";

const BASE = "http://localhost:8080";
const SERVER_FN_BASE = "/_serverFn/";

// Exact serverFnId generated by TanStack Start plugin for loginServerFn
const FN_ID = "eyJmaWxlIjoiL3NyYy9saWIvYXV0aC9sb2dpbi5mdW5jdGlvbi50cz90c3Mtc2VydmVyZm4tc3BsaXQiLCJleHBvcnQiOiJsb2dpblNlcnZlckZuX2NyZWF0ZVNlcnZlckZuX2hhbmRsZXIifQ";

async function main() {
  const url = `${BASE}${SERVER_FN_BASE}${FN_ID}`;
  console.log("=== RAW HTTP REQUEST TO LIVE DEV SERVER ===");
  console.log("POST", url);

  const payload = { data: { email: "phase3test@officemitra.io", password: "Phase3Pass123!" } };
  const serovalBody = JSON.stringify(await toJSONAsync(payload));

  console.log("\nHeaders:");
  console.log("  Content-Type: application/json");
  console.log("  x-tsr-serverFn: true");
  console.log("  accept: application/x-tss-framed, application/x-ndjson, application/json");
  console.log("Body:", serovalBody);

  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-tsr-serverFn": "true",
      "accept": "application/x-tss-framed, application/x-ndjson, application/json",
    },
    body: serovalBody,
  });

  console.log("\n=== RAW HTTP RESPONSE ===");
  console.log("Status:", res.status, res.statusText);
  console.log("Headers:");
  res.headers.forEach((val, key) => {
    console.log(`  ${key}: ${val}`);
  });

  const setCookie = res.headers.get("set-cookie");
  console.log("\nSet-Cookie Header:", setCookie);
  const body = await res.text();
  console.log("Body:", body);

  if (setCookie && setCookie.includes("om_session=")) {
    console.log("\nSUCCESS: Set-Cookie header issued in live HTTP response!");
  } else {
    console.log("\nFAILED: No Set-Cookie header");
  }
}

main().catch(console.error);
