/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as HrRouteImport } from './routes/hr'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyTeamRouteImport } from './routes/my-team'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ProductivityRouteImport } from './routes/productivity'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ScreenshotsRouteImport } from './routes/screenshots'
import { Route as ScreenshotsAgentRouteImport } from './routes/screenshots-agent'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TimesheetsRouteImport } from './routes/timesheets'
import { Route as ApiAdminActivityRouteImport } from './routes/api/admin/activity'
import { Route as ApiAdminScreenshotsRouteImport } from './routes/api/admin/screenshots'
import { Route as ApiConsentActiveRouteImport } from './routes/api/consent/active'
import { Route as ApiConsentBumpRouteImport } from './routes/api/consent/bump'
import { Route as ApiConsentRecordRouteImport } from './routes/api/consent/record'
import { Route as ApiDepartmentsIndexRouteImport } from './routes/api/departments/index'
import { Route as ApiDepartmentsDeleteRouteImport } from './routes/api/departments/delete'
import { Route as ApiDepartmentsUpdateRouteImport } from './routes/api/departments/update'
import { Route as ApiDevicesPairRouteImport } from './routes/api/devices/pair'
import { Route as ApiDevicesRevokeRouteImport } from './routes/api/devices/revoke'
import { Route as ApiEmployeesIndexRouteImport } from './routes/api/employees/index'
import { Route as ApiEmployeesByIdRouteImport } from './routes/api/employees/by-id'
import { Route as ApiEmployeesDeleteRouteImport } from './routes/api/employees/delete'
import { Route as ApiEmployeesInviteRouteImport } from './routes/api/employees/invite'
import { Route as ApiEmployeesUpdateRouteImport } from './routes/api/employees/update'
import { Route as ApiPublicAcceptInviteRouteImport } from './routes/api/public/accept-invite'
import { Route as ApiPublicLoginRouteImport } from './routes/api/public/login'
import { Route as ApiPublicRegisterRouteImport } from './routes/api/public/register'
import { Route as ApiRolesMatrixRouteImport } from './routes/api/roles/matrix'
import { Route as ApiRolesUpdateRouteImport } from './routes/api/roles/update'
import { Route as UploadsScreenshotsFilenameRouteImport } from './routes/uploads/screenshots/$filename'
import { Route as ApiPublicAgentActivityRouteImport } from './routes/api/public/agent.activity'
import { Route as ApiPublicAgentAppLabelsRouteImport } from './routes/api/public/agent.app-labels'
import { Route as ApiPublicAgentBlacklistRouteImport } from './routes/api/public/agent.blacklist'
import { Route as ApiPublicAgentScreenshotsRouteImport } from './routes/api/public/agent.screenshots'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTeamRoute = MyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductivityRoute = ProductivityRouteImport.update({
  id: '/productivity',
  path: '/productivity',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotsRoute = ScreenshotsRouteImport.update({
  id: '/screenshots',
  path: '/screenshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotsAgentRoute = ScreenshotsAgentRouteImport.update({
  id: '/screenshots-agent',
  path: '/screenshots-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetsRoute = TimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminActivityRoute = ApiAdminActivityRouteImport.update({
  id: '/api/admin/activity',
  path: '/api/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminScreenshotsRoute = ApiAdminScreenshotsRouteImport.update({
  id: '/api/admin/screenshots',
  path: '/api/admin/screenshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsentActiveRoute = ApiConsentActiveRouteImport.update({
  id: '/api/consent/active',
  path: '/api/consent/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsentBumpRoute = ApiConsentBumpRouteImport.update({
  id: '/api/consent/bump',
  path: '/api/consent/bump',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsentRecordRoute = ApiConsentRecordRouteImport.update({
  id: '/api/consent/record',
  path: '/api/consent/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDepartmentsIndexRoute = ApiDepartmentsIndexRouteImport.update({
  id: '/api/departments/',
  path: '/api/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDepartmentsDeleteRoute = ApiDepartmentsDeleteRouteImport.update({
  id: '/api/departments/delete',
  path: '/api/departments/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDepartmentsUpdateRoute = ApiDepartmentsUpdateRouteImport.update({
  id: '/api/departments/update',
  path: '/api/departments/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesPairRoute = ApiDevicesPairRouteImport.update({
  id: '/api/devices/pair',
  path: '/api/devices/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesRevokeRoute = ApiDevicesRevokeRouteImport.update({
  id: '/api/devices/revoke',
  path: '/api/devices/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeesIndexRoute = ApiEmployeesIndexRouteImport.update({
  id: '/api/employees/',
  path: '/api/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeesByIdRoute = ApiEmployeesByIdRouteImport.update({
  id: '/api/employees/by-id',
  path: '/api/employees/by-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeesDeleteRoute = ApiEmployeesDeleteRouteImport.update({
  id: '/api/employees/delete',
  path: '/api/employees/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeesInviteRoute = ApiEmployeesInviteRouteImport.update({
  id: '/api/employees/invite',
  path: '/api/employees/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeesUpdateRoute = ApiEmployeesUpdateRouteImport.update({
  id: '/api/employees/update',
  path: '/api/employees/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAcceptInviteRoute = ApiPublicAcceptInviteRouteImport.update({
  id: '/api/public/accept-invite',
  path: '/api/public/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLoginRoute = ApiPublicLoginRouteImport.update({
  id: '/api/public/login',
  path: '/api/public/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegisterRoute = ApiPublicRegisterRouteImport.update({
  id: '/api/public/register',
  path: '/api/public/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRolesMatrixRoute = ApiRolesMatrixRouteImport.update({
  id: '/api/roles/matrix',
  path: '/api/roles/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRolesUpdateRoute = ApiRolesUpdateRouteImport.update({
  id: '/api/roles/update',
  path: '/api/roles/update',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsScreenshotsFilenameRoute =
  UploadsScreenshotsFilenameRouteImport.update({
    id: '/uploads/screenshots/$filename',
    path: '/uploads/screenshots/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentActivityRoute = ApiPublicAgentActivityRouteImport.update({
  id: '/api/public/agent/activity',
  path: '/api/public/agent/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentAppLabelsRoute = ApiPublicAgentAppLabelsRouteImport.update({
  id: '/api/public/agent/app-labels',
  path: '/api/public/agent/app-labels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentBlacklistRoute = ApiPublicAgentBlacklistRouteImport.update({
  id: '/api/public/agent/blacklist',
  path: '/api/public/agent/blacklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentScreenshotsRoute =
  ApiPublicAgentScreenshotsRouteImport.update({
    id: '/api/public/agent/screenshots',
    path: '/api/public/agent/screenshots',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/consent': typeof ConsentRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/hr': typeof HrRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/my-team': typeof MyTeamRoute
  '/policies': typeof PoliciesRoute
  '/productivity': typeof ProductivityRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/screenshots': typeof ScreenshotsRoute
  '/screenshots-agent': typeof ScreenshotsAgentRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/timesheets': typeof TimesheetsRoute
  '/api/admin/activity': typeof ApiAdminActivityRoute
  '/api/admin/screenshots': typeof ApiAdminScreenshotsRoute
  '/api/consent/active': typeof ApiConsentActiveRoute
  '/api/consent/bump': typeof ApiConsentBumpRoute
  '/api/consent/record': typeof ApiConsentRecordRoute
  '/api/departments/delete': typeof ApiDepartmentsDeleteRoute
  '/api/departments/update': typeof ApiDepartmentsUpdateRoute
  '/api/devices/pair': typeof ApiDevicesPairRoute
  '/api/devices/revoke': typeof ApiDevicesRevokeRoute
  '/api/employees/by-id': typeof ApiEmployeesByIdRoute
  '/api/employees/delete': typeof ApiEmployeesDeleteRoute
  '/api/employees/invite': typeof ApiEmployeesInviteRoute
  '/api/employees/update': typeof ApiEmployeesUpdateRoute
  '/api/public/accept-invite': typeof ApiPublicAcceptInviteRoute
  '/api/public/login': typeof ApiPublicLoginRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/roles/matrix': typeof ApiRolesMatrixRoute
  '/api/roles/update': typeof ApiRolesUpdateRoute
  '/uploads/screenshots/$filename': typeof UploadsScreenshotsFilenameRoute
  '/api/departments/': typeof ApiDepartmentsIndexRoute
  '/api/employees/': typeof ApiEmployeesIndexRoute
  '/api/public/agent/activity': typeof ApiPublicAgentActivityRoute
  '/api/public/agent/app-labels': typeof ApiPublicAgentAppLabelsRoute
  '/api/public/agent/blacklist': typeof ApiPublicAgentBlacklistRoute
  '/api/public/agent/screenshots': typeof ApiPublicAgentScreenshotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/consent': typeof ConsentRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/hr': typeof HrRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/my-team': typeof MyTeamRoute
  '/policies': typeof PoliciesRoute
  '/productivity': typeof ProductivityRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/screenshots': typeof ScreenshotsRoute
  '/screenshots-agent': typeof ScreenshotsAgentRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/timesheets': typeof TimesheetsRoute
  '/api/admin/activity': typeof ApiAdminActivityRoute
  '/api/admin/screenshots': typeof ApiAdminScreenshotsRoute
  '/api/consent/active': typeof ApiConsentActiveRoute
  '/api/consent/bump': typeof ApiConsentBumpRoute
  '/api/consent/record': typeof ApiConsentRecordRoute
  '/api/departments/delete': typeof ApiDepartmentsDeleteRoute
  '/api/departments/update': typeof ApiDepartmentsUpdateRoute
  '/api/devices/pair': typeof ApiDevicesPairRoute
  '/api/devices/revoke': typeof ApiDevicesRevokeRoute
  '/api/employees/by-id': typeof ApiEmployeesByIdRoute
  '/api/employees/delete': typeof ApiEmployeesDeleteRoute
  '/api/employees/invite': typeof ApiEmployeesInviteRoute
  '/api/employees/update': typeof ApiEmployeesUpdateRoute
  '/api/public/accept-invite': typeof ApiPublicAcceptInviteRoute
  '/api/public/login': typeof ApiPublicLoginRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/roles/matrix': typeof ApiRolesMatrixRoute
  '/api/roles/update': typeof ApiRolesUpdateRoute
  '/uploads/screenshots/$filename': typeof UploadsScreenshotsFilenameRoute
  '/api/departments': typeof ApiDepartmentsIndexRoute
  '/api/employees': typeof ApiEmployeesIndexRoute
  '/api/public/agent/activity': typeof ApiPublicAgentActivityRoute
  '/api/public/agent/app-labels': typeof ApiPublicAgentAppLabelsRoute
  '/api/public/agent/blacklist': typeof ApiPublicAgentBlacklistRoute
  '/api/public/agent/screenshots': typeof ApiPublicAgentScreenshotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/consent': typeof ConsentRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/hr': typeof HrRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/my-team': typeof MyTeamRoute
  '/policies': typeof PoliciesRoute
  '/productivity': typeof ProductivityRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/screenshots': typeof ScreenshotsRoute
  '/screenshots-agent': typeof ScreenshotsAgentRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/timesheets': typeof TimesheetsRoute
  '/api/admin/activity': typeof ApiAdminActivityRoute
  '/api/admin/screenshots': typeof ApiAdminScreenshotsRoute
  '/api/consent/active': typeof ApiConsentActiveRoute
  '/api/consent/bump': typeof ApiConsentBumpRoute
  '/api/consent/record': typeof ApiConsentRecordRoute
  '/api/departments/delete': typeof ApiDepartmentsDeleteRoute
  '/api/departments/update': typeof ApiDepartmentsUpdateRoute
  '/api/devices/pair': typeof ApiDevicesPairRoute
  '/api/devices/revoke': typeof ApiDevicesRevokeRoute
  '/api/employees/by-id': typeof ApiEmployeesByIdRoute
  '/api/employees/delete': typeof ApiEmployeesDeleteRoute
  '/api/employees/invite': typeof ApiEmployeesInviteRoute
  '/api/employees/update': typeof ApiEmployeesUpdateRoute
  '/api/public/accept-invite': typeof ApiPublicAcceptInviteRoute
  '/api/public/login': typeof ApiPublicLoginRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/roles/matrix': typeof ApiRolesMatrixRoute
  '/api/roles/update': typeof ApiRolesUpdateRoute
  '/uploads/screenshots/$filename': typeof UploadsScreenshotsFilenameRoute
  '/api/departments/': typeof ApiDepartmentsIndexRoute
  '/api/employees/': typeof ApiEmployeesIndexRoute
  '/api/public/agent/activity': typeof ApiPublicAgentActivityRoute
  '/api/public/agent/app-labels': typeof ApiPublicAgentAppLabelsRoute
  '/api/public/agent/blacklist': typeof ApiPublicAgentBlacklistRoute
  '/api/public/agent/screenshots': typeof ApiPublicAgentScreenshotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/consent'
    | '/departments'
    | '/employees'
    | '/hr'
    | '/invite'
    | '/login'
    | '/my-team'
    | '/policies'
    | '/productivity'
    | '/projects'
    | '/reports'
    | '/roles'
    | '/screenshots'
    | '/screenshots-agent'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/timesheets'
    | '/api/admin/activity'
    | '/api/admin/screenshots'
    | '/api/consent/active'
    | '/api/consent/bump'
    | '/api/consent/record'
    | '/api/departments/delete'
    | '/api/departments/update'
    | '/api/devices/pair'
    | '/api/devices/revoke'
    | '/api/employees/by-id'
    | '/api/employees/delete'
    | '/api/employees/invite'
    | '/api/employees/update'
    | '/api/public/accept-invite'
    | '/api/public/login'
    | '/api/public/register'
    | '/api/roles/matrix'
    | '/api/roles/update'
    | '/uploads/screenshots/$filename'
    | '/api/departments/'
    | '/api/employees/'
    | '/api/public/agent/activity'
    | '/api/public/agent/app-labels'
    | '/api/public/agent/blacklist'
    | '/api/public/agent/screenshots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/consent'
    | '/departments'
    | '/employees'
    | '/hr'
    | '/invite'
    | '/login'
    | '/my-team'
    | '/policies'
    | '/productivity'
    | '/projects'
    | '/reports'
    | '/roles'
    | '/screenshots'
    | '/screenshots-agent'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/timesheets'
    | '/api/admin/activity'
    | '/api/admin/screenshots'
    | '/api/consent/active'
    | '/api/consent/bump'
    | '/api/consent/record'
    | '/api/departments/delete'
    | '/api/departments/update'
    | '/api/devices/pair'
    | '/api/devices/revoke'
    | '/api/employees/by-id'
    | '/api/employees/delete'
    | '/api/employees/invite'
    | '/api/employees/update'
    | '/api/public/accept-invite'
    | '/api/public/login'
    | '/api/public/register'
    | '/api/roles/matrix'
    | '/api/roles/update'
    | '/uploads/screenshots/$filename'
    | '/api/departments'
    | '/api/employees'
    | '/api/public/agent/activity'
    | '/api/public/agent/app-labels'
    | '/api/public/agent/blacklist'
    | '/api/public/agent/screenshots'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/consent'
    | '/departments'
    | '/employees'
    | '/hr'
    | '/invite'
    | '/login'
    | '/my-team'
    | '/policies'
    | '/productivity'
    | '/projects'
    | '/reports'
    | '/roles'
    | '/screenshots'
    | '/screenshots-agent'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/timesheets'
    | '/api/admin/activity'
    | '/api/admin/screenshots'
    | '/api/consent/active'
    | '/api/consent/bump'
    | '/api/consent/record'
    | '/api/departments/delete'
    | '/api/departments/update'
    | '/api/devices/pair'
    | '/api/devices/revoke'
    | '/api/employees/by-id'
    | '/api/employees/delete'
    | '/api/employees/invite'
    | '/api/employees/update'
    | '/api/public/accept-invite'
    | '/api/public/login'
    | '/api/public/register'
    | '/api/roles/matrix'
    | '/api/roles/update'
    | '/uploads/screenshots/$filename'
    | '/api/departments/'
    | '/api/employees/'
    | '/api/public/agent/activity'
    | '/api/public/agent/app-labels'
    | '/api/public/agent/blacklist'
    | '/api/public/agent/screenshots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ConsentRoute: typeof ConsentRoute
  DepartmentsRoute: typeof DepartmentsRoute
  EmployeesRoute: typeof EmployeesRoute
  HrRoute: typeof HrRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  MyTeamRoute: typeof MyTeamRoute
  PoliciesRoute: typeof PoliciesRoute
  ProductivityRoute: typeof ProductivityRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  RolesRoute: typeof RolesRoute
  ScreenshotsRoute: typeof ScreenshotsRoute
  ScreenshotsAgentRoute: typeof ScreenshotsAgentRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  TimesheetsRoute: typeof TimesheetsRoute
  ApiAdminActivityRoute: typeof ApiAdminActivityRoute
  ApiAdminScreenshotsRoute: typeof ApiAdminScreenshotsRoute
  ApiConsentActiveRoute: typeof ApiConsentActiveRoute
  ApiConsentBumpRoute: typeof ApiConsentBumpRoute
  ApiConsentRecordRoute: typeof ApiConsentRecordRoute
  ApiDepartmentsDeleteRoute: typeof ApiDepartmentsDeleteRoute
  ApiDepartmentsUpdateRoute: typeof ApiDepartmentsUpdateRoute
  ApiDevicesPairRoute: typeof ApiDevicesPairRoute
  ApiDevicesRevokeRoute: typeof ApiDevicesRevokeRoute
  ApiEmployeesByIdRoute: typeof ApiEmployeesByIdRoute
  ApiEmployeesDeleteRoute: typeof ApiEmployeesDeleteRoute
  ApiEmployeesInviteRoute: typeof ApiEmployeesInviteRoute
  ApiEmployeesUpdateRoute: typeof ApiEmployeesUpdateRoute
  ApiPublicAcceptInviteRoute: typeof ApiPublicAcceptInviteRoute
  ApiPublicLoginRoute: typeof ApiPublicLoginRoute
  ApiPublicRegisterRoute: typeof ApiPublicRegisterRoute
  ApiRolesMatrixRoute: typeof ApiRolesMatrixRoute
  ApiRolesUpdateRoute: typeof ApiRolesUpdateRoute
  UploadsScreenshotsFilenameRoute: typeof UploadsScreenshotsFilenameRoute
  ApiDepartmentsIndexRoute: typeof ApiDepartmentsIndexRoute
  ApiEmployeesIndexRoute: typeof ApiEmployeesIndexRoute
  ApiPublicAgentActivityRoute: typeof ApiPublicAgentActivityRoute
  ApiPublicAgentAppLabelsRoute: typeof ApiPublicAgentAppLabelsRoute
  ApiPublicAgentBlacklistRoute: typeof ApiPublicAgentBlacklistRoute
  ApiPublicAgentScreenshotsRoute: typeof ApiPublicAgentScreenshotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-team': {
      id: '/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof MyTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productivity': {
      id: '/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof ProductivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshots': {
      id: '/screenshots'
      path: '/screenshots'
      fullPath: '/screenshots'
      preLoaderRoute: typeof ScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshots-agent': {
      id: '/screenshots-agent'
      path: '/screenshots-agent'
      fullPath: '/screenshots-agent'
      preLoaderRoute: typeof ScreenshotsAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheets': {
      id: '/timesheets'
      path: '/timesheets'
      fullPath: '/timesheets'
      preLoaderRoute: typeof TimesheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/activity': {
      id: '/api/admin/activity'
      path: '/api/admin/activity'
      fullPath: '/api/admin/activity'
      preLoaderRoute: typeof ApiAdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/screenshots': {
      id: '/api/admin/screenshots'
      path: '/api/admin/screenshots'
      fullPath: '/api/admin/screenshots'
      preLoaderRoute: typeof ApiAdminScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consent/active': {
      id: '/api/consent/active'
      path: '/api/consent/active'
      fullPath: '/api/consent/active'
      preLoaderRoute: typeof ApiConsentActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consent/bump': {
      id: '/api/consent/bump'
      path: '/api/consent/bump'
      fullPath: '/api/consent/bump'
      preLoaderRoute: typeof ApiConsentBumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consent/record': {
      id: '/api/consent/record'
      path: '/api/consent/record'
      fullPath: '/api/consent/record'
      preLoaderRoute: typeof ApiConsentRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/departments/': {
      id: '/api/departments/'
      path: '/api/departments'
      fullPath: '/api/departments/'
      preLoaderRoute: typeof ApiDepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/departments/delete': {
      id: '/api/departments/delete'
      path: '/api/departments/delete'
      fullPath: '/api/departments/delete'
      preLoaderRoute: typeof ApiDepartmentsDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/departments/update': {
      id: '/api/departments/update'
      path: '/api/departments/update'
      fullPath: '/api/departments/update'
      preLoaderRoute: typeof ApiDepartmentsUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/pair': {
      id: '/api/devices/pair'
      path: '/api/devices/pair'
      fullPath: '/api/devices/pair'
      preLoaderRoute: typeof ApiDevicesPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/revoke': {
      id: '/api/devices/revoke'
      path: '/api/devices/revoke'
      fullPath: '/api/devices/revoke'
      preLoaderRoute: typeof ApiDevicesRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees/': {
      id: '/api/employees/'
      path: '/api/employees'
      fullPath: '/api/employees/'
      preLoaderRoute: typeof ApiEmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees/by-id': {
      id: '/api/employees/by-id'
      path: '/api/employees/by-id'
      fullPath: '/api/employees/by-id'
      preLoaderRoute: typeof ApiEmployeesByIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees/delete': {
      id: '/api/employees/delete'
      path: '/api/employees/delete'
      fullPath: '/api/employees/delete'
      preLoaderRoute: typeof ApiEmployeesDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees/invite': {
      id: '/api/employees/invite'
      path: '/api/employees/invite'
      fullPath: '/api/employees/invite'
      preLoaderRoute: typeof ApiEmployeesInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees/update': {
      id: '/api/employees/update'
      path: '/api/employees/update'
      fullPath: '/api/employees/update'
      preLoaderRoute: typeof ApiEmployeesUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/accept-invite': {
      id: '/api/public/accept-invite'
      path: '/api/public/accept-invite'
      fullPath: '/api/public/accept-invite'
      preLoaderRoute: typeof ApiPublicAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/login': {
      id: '/api/public/login'
      path: '/api/public/login'
      fullPath: '/api/public/login'
      preLoaderRoute: typeof ApiPublicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/register': {
      id: '/api/public/register'
      path: '/api/public/register'
      fullPath: '/api/public/register'
      preLoaderRoute: typeof ApiPublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roles/matrix': {
      id: '/api/roles/matrix'
      path: '/api/roles/matrix'
      fullPath: '/api/roles/matrix'
      preLoaderRoute: typeof ApiRolesMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roles/update': {
      id: '/api/roles/update'
      path: '/api/roles/update'
      fullPath: '/api/roles/update'
      preLoaderRoute: typeof ApiRolesUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/screenshots/$filename': {
      id: '/uploads/screenshots/$filename'
      path: '/uploads/screenshots/$filename'
      fullPath: '/uploads/screenshots/$filename'
      preLoaderRoute: typeof UploadsScreenshotsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/activity': {
      id: '/api/public/agent/activity'
      path: '/api/public/agent/activity'
      fullPath: '/api/public/agent/activity'
      preLoaderRoute: typeof ApiPublicAgentActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/app-labels': {
      id: '/api/public/agent/app-labels'
      path: '/api/public/agent/app-labels'
      fullPath: '/api/public/agent/app-labels'
      preLoaderRoute: typeof ApiPublicAgentAppLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/blacklist': {
      id: '/api/public/agent/blacklist'
      path: '/api/public/agent/blacklist'
      fullPath: '/api/public/agent/blacklist'
      preLoaderRoute: typeof ApiPublicAgentBlacklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/screenshots': {
      id: '/api/public/agent/screenshots'
      path: '/api/public/agent/screenshots'
      fullPath: '/api/public/agent/screenshots'
      preLoaderRoute: typeof ApiPublicAgentScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  ConsentRoute: ConsentRoute,
  DepartmentsRoute: DepartmentsRoute,
  EmployeesRoute: EmployeesRoute,
  HrRoute: HrRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  MyTeamRoute: MyTeamRoute,
  PoliciesRoute: PoliciesRoute,
  ProductivityRoute: ProductivityRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  RolesRoute: RolesRoute,
  ScreenshotsRoute: ScreenshotsRoute,
  ScreenshotsAgentRoute: ScreenshotsAgentRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  TimesheetsRoute: TimesheetsRoute,
  ApiAdminActivityRoute: ApiAdminActivityRoute,
  ApiAdminScreenshotsRoute: ApiAdminScreenshotsRoute,
  ApiConsentActiveRoute: ApiConsentActiveRoute,
  ApiConsentBumpRoute: ApiConsentBumpRoute,
  ApiConsentRecordRoute: ApiConsentRecordRoute,
  ApiDepartmentsDeleteRoute: ApiDepartmentsDeleteRoute,
  ApiDepartmentsUpdateRoute: ApiDepartmentsUpdateRoute,
  ApiDevicesPairRoute: ApiDevicesPairRoute,
  ApiDevicesRevokeRoute: ApiDevicesRevokeRoute,
  ApiEmployeesByIdRoute: ApiEmployeesByIdRoute,
  ApiEmployeesDeleteRoute: ApiEmployeesDeleteRoute,
  ApiEmployeesInviteRoute: ApiEmployeesInviteRoute,
  ApiEmployeesUpdateRoute: ApiEmployeesUpdateRoute,
  ApiPublicAcceptInviteRoute: ApiPublicAcceptInviteRoute,
  ApiPublicLoginRoute: ApiPublicLoginRoute,
  ApiPublicRegisterRoute: ApiPublicRegisterRoute,
  ApiRolesMatrixRoute: ApiRolesMatrixRoute,
  ApiRolesUpdateRoute: ApiRolesUpdateRoute,
  UploadsScreenshotsFilenameRoute: UploadsScreenshotsFilenameRoute,
  ApiDepartmentsIndexRoute: ApiDepartmentsIndexRoute,
  ApiEmployeesIndexRoute: ApiEmployeesIndexRoute,
  ApiPublicAgentActivityRoute: ApiPublicAgentActivityRoute,
  ApiPublicAgentAppLabelsRoute: ApiPublicAgentAppLabelsRoute,
  ApiPublicAgentBlacklistRoute: ApiPublicAgentBlacklistRoute,
  ApiPublicAgentScreenshotsRoute: ApiPublicAgentScreenshotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
